export {
  acceptDua,
  assignDua,
  deletePhoto,
  getCapsuleStatus,
  getEventStats,
  getGuestMe,
  getQuestionnaire,
  initGuest,
  listPhotos,
  submitAdvice,
  submitVote,
  uploadCapsule,
  uploadPhoto,
} from "./guest.service";
